export enum SCREENS {
  ROOT = "ROOT_NAVIGATION",
  LAUNCH_SCREEN = "LAUNCH_SCREEN",
  HOME_STACK = "HOME_STACK",
  HOME_SCREEN = "HOME_SCREEN",
  DETAIL_SCREEN = "DETAIL_SCREEN",
  INFO_SCREEN = "INFO_SCREEN",
}
